src/magplan/urls.py
# from django.conf.urls import url
from django.urls import path

from magplan.views import (
    api,
    articles,
    authors,
    ideas,
    index,
    issues,
    posts,
    preferences,
    sections,
    stages,
)

urlpatterns = [
    path("sections/", sections.index, name="sections_index"),
    path("stages/", stages.index, name="stages_index"),
    path(
        "ideas/<int:idea_id>/comments/", ideas.comments, name="ideas_comments"
    ),
    path("ideas/<int:idea_id>/approve/", ideas.approve, name="ideas_approve"),
    path("ideas/<int:idea_id>/vote/", ideas.vote, name="ideas_vote"),
    path("ideas/<int:idea_id>/", ideas.show, name="ideas_show"),
    path("ideas/", ideas.index, name="ideas_index"),
    path("articles/search", articles.search, name="articles_search"),
    path("articles/default", articles.default, name="articles_default"),
    path("articles/archived", articles.archived, name="articles_archived"),
    path("articles/advert", articles.advert, name="articles_advert"),
    path(
        "articles/whitelisted",
        articles.whitelisted,
        name="articles_whitelisted",
    ),
    path("articles/", articles.index, name="articles_index"),
    path("issues/<int:issue_id>/", issues.show, name="issues_show"),
    path("issues/new/", issues.create, name="issues_create"),
    path("issues/", issues.index, name="issues_index"),
    path(
        "posts/<int:post_id>/attachments/delete/",
        posts.attachment_delete,
        name="posts_attachment_delete",
    ),
    path(
        "posts/<int:post_id>/comments/", posts.comments, name="posts_comments"
    ),
    path(
        "posts/<int:post_id>/set_stage/",
        posts.set_stage,
        name="posts_set_stage",
    ),
    path("posts/<int:post_id>/edit/", posts.edit, name="posts_edit"),
    path(
        "posts/<int:post_id>/edit_meta/",
        posts.edit_meta,
        name="posts_edit_meta",
    ),
    path(
        "posts/<int:post_id>/download/",
        posts.download_content,
        name="posts_download_content",
    ),
    path(
        "posts/<int:post_id>/send_to_wp/",
        posts.send_to_wp,
        name="posts_send_to_wp",
    ),
    path("posts/<int:post_id>/", posts.show, name="posts_show"),
    path("posts", posts.create, name="posts_create"),
    path("api/issues/search/", api.issues_search, name="api_issues_search"),
    path("api/users/search/", api.authors_search, name="api_authors_search"),
    path("authors/new/", authors.new, name="authors_new"),
    path("authors/<int:user_id>/edit/", authors.edit, name="authors_edit"),
    path("authors/<int:user_id>/", authors.show, name="authors_show"),
    path("authors/", authors.index, name="authors_index"),
    path("settings/", preferences.index, name="preferences_index"),
    path("", index.index, name="index_index"),
]

src/magplan/models/post.py
import datetime
import enum
import hashlib
import logging
import mimetypes
import os
import typing as tp
import urllib
from typing import List

import django
import requests
from botocore.exceptions import ClientError
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models import JSONField
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone

from magplan.conf import settings as config
from magplan.conf.settings import S3_STATIC_BASE_PATH
from magplan.integrations.images import S3Client
from magplan.integrations.posts import replace_images_paths, update_ext_db_xmd
from magplan.models import User
from magplan.models.abs import AbstractSiteModel, AbstractBase
from magplan.models.issue import Issue
from magplan.models.section import Section
from magplan.models.stage import Stage
from magplan.models.user import User
from magplan.xmd import render_md
from magplan.xmd.mappers import s3_public_mapper as s3_image_mapper, plan_internal_mapper as plan_image_mapper

WP_DATE_FORMAT_STRING = "%Y-%m-%d %H:%M:%S"
logger = logging.getLogger()


class Post(AbstractSiteModel, AbstractBase):
    # Used for external parser configuration
    PAYWALL_NOTICE_HEAD = '<div class="paywall-notice">'
    PAYWALL_NOTICE_BODY = "Продолжение статьи доступно только продписчикам"
    PAYWALL_NOTICE_TAIL = "</div>"
    PAYWALL_NOTICE_RENDERED = "{}{}{}".format(
        PAYWALL_NOTICE_HEAD, PAYWALL_NOTICE_BODY, PAYWALL_NOTICE_TAIL
    )

    @property
    def full_title(self) -> str:
        if self.kicker is None:
            return self.title

        separator = " " if self.kicker.endswith(("!", ":", "?")) else ". "
        return f"{self.kicker}{separator}{self.title}"

    def __str__(self) -> str:
        return self.full_title

    POST_FORMAT_DEFAULT = 0
    POST_FORMAT_FEATURED = 1
    POST_FORMAT_CHOICES = (
        (POST_FORMAT_DEFAULT, "Default"),
        (POST_FORMAT_FEATURED, "Featured"),
    )

    format = models.SmallIntegerField(
        choices=POST_FORMAT_CHOICES, default=POST_FORMAT_DEFAULT
    )

    POST_FEATURES_DEFAULT = 0
    POST_FEATURES_ARCHIVE = 1
    POST_FEATURES_ADVERT = 2
    POST_FEATURES_TRANSLATED = 2
    POST_FEATURES_CHOICES = (
        (POST_FEATURES_DEFAULT, "Default"),
        (POST_FEATURES_ARCHIVE, "Archive"),
        (POST_FEATURES_ADVERT, "Advert"),
        (POST_FEATURES_TRANSLATED, "Translated"),
    )
    features = models.SmallIntegerField(
        choices=POST_FEATURES_CHOICES, default=POST_FEATURES_DEFAULT
    )

    finished_at = models.DateTimeField(
        null=False,
        blank=False,
        default=django.utils.timezone.now,
        verbose_name="Дедлайн",
    )
    published_at = models.DateTimeField(
        null=True, blank=True, verbose_name="Дата публикации"
    )
    kicker = models.CharField(null=True, blank=True, max_length=255)
    slug = models.SlugField(
        null=True, blank=True, max_length=255, verbose_name="Слаг для URL"
    )
    title = models.CharField(
        null=True, blank=True, max_length=255, verbose_name="Заголовок статьи"
    )
    description = models.TextField(
        null=False, blank=True, verbose_name="Описание статьи"
    )
    views = models.IntegerField(default=0)
    is_paywalled = models.BooleanField(default=False)
    xmd = models.TextField(null=True)
    html = models.TextField(null=True)

    editor = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name="edited",
        verbose_name="Редактор",
    )
    authors = models.ManyToManyField(User, verbose_name="Авторы")
    stage = models.ForeignKey(
        Stage, on_delete=models.CASCADE, verbose_name="Этап"
    )
    issues = models.ManyToManyField(
        Issue, related_name="posts", verbose_name="Выпуски"
    )
    section = models.ForeignKey(
        Section,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        verbose_name="Раздел",
    )
    last_updater = models.ForeignKey(
        User,
        related_name="posts_updated",
        verbose_name="Кто последний обновлял",
        null=True,
        on_delete=models.SET_NULL,
    )

    meta = JSONField(default=dict)

    comments = GenericRelation("Comment")
    is_locked = models.BooleanField(default=False)
    css = models.TextField(
        null=True,
        blank=True,
        verbose_name="CSS-стили для статьи",
        help_text=("CSS, который будет применяться к превью статьи"),
    )

    def imprint_updater(self, user: User) -> None:
        """Update updated_at timestamp and set provided user as last_updater.

        `created_at` may be overwritten further on DB-hook level.
        .save() method should be explicitly called.
        """
        self.last_updater = user
        self.updated_at = datetime.datetime.now()

    @property
    def images(self):
        return list(
            filter(
                lambda a: a.type == Attachment.TYPE_IMAGE,
                self.attachment_set.all(),
            )
        )

    @property
    def pdfs(self):
        return list(
            filter(
                lambda a: a.type == Attachment.TYPE_PDF,
                self.attachment_set.all(),
            )
        )

    @property
    def files(self):
        return list(
            filter(
                lambda a: a.type == Attachment.TYPE_FILE,
                self.attachment_set.all(),
            )
        )

    @property
    def featured_image(self) -> tp.Optional["Attachment"]:
        return self.attachment_set.filter(
            type=Attachment.TYPE_FEATURED_IMAGE
        ).first()

    @property
    def assignee(self):
        if self.stage and self.stage.assignee:
            return self.stage.assignee
        elif self.editor:
            return self.editor
        else:
            return None

    @property
    def prev_stage_assignee(self):
        if self.stage.prev_stage and self.stage.prev_stage.assignee:
            return self.stage.prev_stage.assignee
        else:
            return self.editor

    @property
    def next_stage_assignee(self):
        if self.stage.next_stage and self.stage.next_stage.assignee:
            return self.stage.next_stage.assignee
        else:
            return self.editor

    @property
    def comments_(self):
        return self.comments.order_by("created_at").all

    @property
    def has_text(self):
        return self.xmd is not None and self.xmd != ""

    @property
    def is_default(self):
        return self.features == self.POST_FEATURES_DEFAULT

    @property
    def is_archive(self):
        return self.features == self.POST_FEATURES_ARCHIVE

    @property
    def is_advert(self):
        return self.features == self.POST_FEATURES_ADVERT

    @property
    def is_regular(self):
        return self.section.is_whitelisted == True

    @property
    def is_translated(self):
        return self.features == self.POST_FEATURES_TRANSLATED

    class Meta:
        permissions = (
            ("recieve_post_email_updates", "Recieve email updates for Post"),
            ("edit_extended_post_attrs", "Edit extended Post attributes"),
            # Direct article creation
            ("create_generic_post", "Create generic post"),
            ("create_archive_post", "Create archive post"),
            ("create_advert_post", "Create advert post"),
            ("create_regular_post", "Create regular post"),
            ("create_translated_post", "Create translated post"),
        )

    @property
    def is_overdue(self):
        if self.stage.slug in ("vault", "published"):
            return False
        return timezone.now() > self.finished_at

    @property
    def description_html(self):
        return render_md(self.description, render_lead=False)

    @property
    def wp_id(self):
        return self.meta.get("wpid")

    @property
    def lead(self) -> str:
        if not self.xmd:
            return ""

        paragraphs: List[str] = self.xmd.split("\n")
        for paragraph in paragraphs:
            cleaned_paragraph = paragraph.strip()
            if not cleaned_paragraph:
                continue

            if cleaned_paragraph.startswith("$"):
                cleaned_paragraph = cleaned_paragraph[1:]

            cleaned_paragraph = cleaned_paragraph.strip()
            return cleaned_paragraph

        return ""

    def build_xmd_blob(self, prepared_xmd: str) -> str:
        """Attaches CSS to XMD for remote CMS

        >>> self.css ='foo'
        'foo'

        >>> xmd = 'bar'
        'bar'

        >>> self.build_xmd_blob(self.xmd)
        %style type=text/css
        foo
        %style
        bar
        """
        OPENING_STYLE_TAG = "%style type=text/css"
        CLOSING_STYLE_TAG = "%style"

        if not prepared_xmd:
            return prepared_xmd

        if not self.css:
            return prepared_xmd

        return "{}\n{}\n{}\n{}".format(
            OPENING_STYLE_TAG, self.css, CLOSING_STYLE_TAG, prepared_xmd
        )

    def upload(self):
        """Uploads post, metadata and attachments to remote CMS

        * self images uploaded to S3.
        * self content uploaded to WP with uploaded S3 images urls

        This method is long-running, can cause time-outs
        and should be run ONLY in async tasks.
        """
        logger.debug("Staring Post.upload")
        if not self.wp_id:
            logger.warning("No wp_id, exiting")
            return

        for image in self.images:
            image.upload_to_storage()
        logger.debug("Uploaded images")

        # Upload to external DB
        prepared_xmd = replace_images_paths(
            xmd=self.xmd,
            attachments=self.images,
            mapper=s3_image_mapper,
        )
        logger.debug("Replaced images paths")

        upload_kwargs: tp.Dict[str, str] = {
            "xmd": prepared_xmd,
            "title": str(self),

src/magplan/models/stage.py
from django.db import models
from django.db.models import JSONField

from magplan.models.abs import AbstractSiteModel, AbstractBase
from magplan.models.user import User


class Stage(AbstractSiteModel, AbstractBase):
    def __str__(self):
        return self.title

    slug = models.SlugField(null=False, blank=False, max_length=255)
    title = models.CharField(null=False, blank=False, max_length=255)
    sort = models.SmallIntegerField(null=False, blank=False, default=0)
    duration = models.SmallIntegerField(null=True, blank=True, default=1)
    assignee = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.CASCADE
    )
    prev_stage = models.ForeignKey(
        "self",
        related_name="n_stage",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    next_stage = models.ForeignKey(
        "self",
        related_name="p_stage",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    skip_notification = models.BooleanField(
        null=False, blank=False, default=False
    )
    meta = JSONField(default=dict)

src/magplan/views/stages.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from magplan.models import Stage


# Create your views here.
@login_required
def index(request):
    return render(
        request,
        "magplan/stages/index.html",
        {
            "stages": (
                Stage.objects.order_by("sort")
                .all()
                .prefetch_related("prev_stage", "next_stage", "assignee")
            )
        },
    )

src/magplan/templates/magplan/posts/_admin_set_stage.html
<a class="" data-toggle="collapse" href="#admin_move" role="button" aria-expanded="false"
   aria-controls="admin_move">
    Изменить этап
</a>


<div class="admin_move collapse" id="admin_move">
    <hr/>
    <form action="{% url 'posts_set_stage' post.id %}" method="post" accept-charset="utf-8">
        <div class="form-group">
            {% csrf_token %}
            <label for="exampleFormControlSelect1">Подвинуть на произвольный этап как админ:</label>
            <select class="form-control" name="new_stage_id">
                {% for stage in stages %}
                    <option value="{{ stage.id }}"
                            {% if stage.id == post.stage.id %}selected{% endif %}>{{ stage.title }}</option>
                {% endfor %}
            </select>
        </div>
        <input type="submit" class="btn btn-block btn-primary" value="Изменить этап"/>
    </form>
</div>

src/magplan/templates/magplan/posts/_field_col.html
{% load filters %}

{% with field=form|get_item:field %}
    <div class="col-xl-{{ size }} col-lg-{{ size }} col-md-{{ size }} col-sm-12">
        {% if field.field.widget.is_hidden is True %}
            {{ field }}
        {% else %}
            <div class="form-group">
                {% if field.field.widget.is_hidden is False %}
                    {{ field.label }}
                {% endif %}

                {% if field.errors %}
                    <ul class="errors">
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {{ field }}
            </div>
        {% endif %}
    </div>
{% endwith %}

src/magplan/templates/magplan/posts/_form_base.html
{% load widget_tweaks %}

<style>
    .issues-suggestions .suggestion {
        display: inline;
        margin-right: 0.2rem;
    }

    .issues-suggestions .suggestion a {
        text-decoration: underline;
        text-decoration-style: dotted;
    }
</style>
<div class="row">
    <div class="col-12">
        <div class="form-group">
            {{ form.title.label }}
            {% if form.title.errors %}
            <ul class="errors">
                {% for error in form.title.errors %}
                <li>{{ error }}</li>{% endfor %}
            </ul>
            {% endif %}
            {{ form.title }}
        </div>
    </div>
</div>
<div class="row edit_hidden">
    <div class="col-12">
        <div class="form-group">
            {{ form.description.label }}
            {% if form.description.errors %}
            <ul class="errors">
                {% for error in form.description.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {{ form.description }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="form-group">
            {{ form.section.label }}
            {% if form.section.errors %}
            <ul class="errors">
                {% for error in form.section_id.errors %}
                <li>{{ error }}</li>{% endfor %}
            </ul>
            {% endif %}
            {{ form.section }}
        </div>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="form-group">
            {{ form.issues.label }}
            {% if form.issues.errors %}
            <ul class="errors">
                {% for error in form.issues.errors %}
                <li>{{ error }}</li>{% endfor %}
            </ul>
            {% endif %}

            {% render_field form.issues data-url=api_issues_search_url %}

            <div class="issues-suggestions">
                {% for issue in issues_suggesions %}
                <div class="suggestion">
                    <a href="#" class="text-success"data-id="{{ issue.id }}">{{ issue }}</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">
        <div class="form-group">
            {{ form.authors.label }}
            {% if form.authors.errors %}
            <ul class="errors">
                {% for error in form.authors.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% render_field form.authors data-url=api_authors_search_url %}
        </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
        <div class="form-group">
            {{ form.finished_at.label }}
            {% if form.finished_at.errors %}
            <ul class="errors">
                {% for error in form.finished_at.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <input type="text" name="finished_at" value="{{ form.finished_at.value|date:'Y-m-d' }}"
                class="form-control date_picker" required="" id="id_finished_at">
            {#            {{ form.finished_at }}#}
        </div>
    </div>
</div>

src/magplan/templates/magplan/posts/_paywall_alert.html
{% if post.is_paywalled == True %}
    <div class="bd-callout" role="alert">
        Публикуется с пейволлом
    </div>
{% else %}
    <div class="bd-callout bd-callout-info" role="alert">
        Публикуется без пейволла
    </div>
{% endif%}

src/magplan/templates/magplan/posts/_progress.html
{% load filters %}
<div class="row" id="progress">
    <div class="col-12">
        <div class="progress" style="height: 1.6rem;">
            {% with stages_count=stages|length %}
                {% with barwidth=100|divide:stages_count current_rendered=False %}
                    {% for stage in stages %}
                        {% if current_rendered == False %}
                            <div class="progress-bar progress-bar progress-bar-striped" role="progressbar"
                                 style="width: {{ barwidth }}%; background-color: #{{ stage.meta.background }};
                                         color: #{{ stage.meta.foreground }}; font-weight: bold;"
                                 aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{ stage.title }}</div>
                        {% endif %}
                        {% if stage.id == post.stage.id %}{% set current_rendered = True %}{% endif %}
                    {% endfor %}
                {% endwith %}
            {% endwith %}

        </div>
    </div>
</div>

src/magplan/templates/magplan/posts/_schedule.html
{% if perms.magplan.schedule_publish %}
    <div class="row">
        <div class="col-12">
            <h4>Запланировать публикацию</h4>
        </div>
    </div>
    <form action="{% url 'posts_schedule' post_id=post.id %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <input type="text" name="published_at" value="{{ post.published_at|date:'Y-m-d' }}"
                           class="form-control date_picker" required="" id="id_published_at">
                </div>
            </div>
            <div class="col-8">
                <div class="form-group">
                    <input type="submit" value="Запланировать" class="btn btn-success">
                </div>
            </div>
        </div>
    </form>
{% endif %}

src/magplan/templates/magplan/posts/edit.html
{% extends "layout_plan.html" %}
{% load filters %}
{% load widget_tweaks %}

{% block title %}Редактирование «{{ post.title }}»{% endblock %}
{% block styles %}
    <style>
        .attachment-image {
            overflow: hidden;
            background-size: cover;
            background-position: center;
            height: 8rem;
        }

        span.twitter-typeahead {
            width: auto !important;
        }

        section {
            padding-bottom: 1rem;
        }

        #editor {
            position: relative;
            height: 40rem;
        }

        .select2-container {
            width: 100% !important;
        }

        #header h1 {
            display: inline;
            font-weight: bold;
        }

        .edit_hidden {
            display: none;
        }

        #images_status > p {
            color: #ddd;
        }

        #images_status > #missing.active {
            color: lightcoral;
        }

        #images_status > #extra.active {
            /* Also red, as extra image is also treated as error */
            /* color: cadetblue; */
            color: lightcoral;
        }

        footer {
            z-index: 1;
        }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block content %}
    {% if post.is_locked == True %}
        <div class="flash_messages">
            <div class="alert alert-warning" role="alert">
                Этот пост сейчас публикуется в Wordpress. Пожалуйта, не редактируйте его до окончания обновления.
                Вы можете обновить страницу чтобы убедиться, что публикация завершена.
            </div>
        </div>
    {% endif %}

    <h2>Редактирование «<a href="{% url 'posts_show' post.id %}">{{ post }}</a>»</h2>
    <div class="meta">
        <p>В номерах: {% for issue in post.issues.all %}
            <a href="{% url 'issues_show' issue.id %}">{{ issue }}</a>{% if forloop.last is False %}, {% else %}.
            {% endif %}
        {% endfor %}</p>
    </div>
    <form id="save_post_form"
          action="{% url 'posts_edit' post.id %}"
          method="post"
          accept-charset="utf-8"
          enctype='multipart/form-data'>
        {% csrf_token %}

        <div class="row">
            {% with field="kicker" size=4 %}{% include 'magplan/posts/_field_col.html' %}{% endwith %}
            {% with field="title" size=8 %}{% include 'magplan/posts/_field_col.html' %}{% endwith %}
            {% with field="description" size=12 %}{% include 'magplan/posts/_field_col.html' %}{% endwith %}
            {% with field="section" size=6 %}{% include 'magplan/posts/_field_col.html' %}{% endwith %}
            {% with field_name="authors" size=6 %}
                {% with field=form|get_item:field_name %}
                    <div class="col-xl-{{ size }} col-lg-{{ size }} col-md-{{ size }} col-sm-12">
                        {% if field.field.widget.is_hidden is True %}
                            {{ field }}
                        {% else %}
                            <div class="form-group">
                                {% if field.field.widget.is_hidden is False %}
                                    {{ field.label }}
                                {% endif %}

                                {% if field.errors %}
                                    <ul class="errors">
                                        {% for error in field.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                {% render_field field data-url=api_authors_search_url %}
                            </div>
                        {% endif %}
                    </div>
                {% endwith %}
            {% endwith %}
        </div>


        <section id="attachments" style="margin-bottom: 1rem;">
            {% with is_locked=post.is_locked images=post.images pdfs=post.pdfs files=post.files featured_image=post.featured_image %}
                {% include 'magplan/posts/_attachments.html' %}
            {% endwith %}

            <div id="images_status">
                <p id="missing"></p>
                <p id="extra"></p>
            </div>
        </section>

        <div class="row">
            {% with field="xmd" size=12 %}{% include 'magplan/posts/_field_col.html' %}{% endwith %}
        </div>
    </form>
{% endblock %}

{% block footer %}
    <footer class="footer">
        <div class="container">
            <span class="small d-none d-sm-inline">Изменено {{ post.updated_at }}{% if post.last_updater %} —
                {{ post.last_updater }}{% endif %}</span>
            <div class="float-right">
                <input type="submit" id="save_post" form="save_post_form"
                       class="btn btn-success" value="Сохранить"
                       {% if post.is_locked == True %}disabled="disabled"{% endif %}
                />
            </div>
        </div>
    </footer>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        window.DELETE_ATTACHMENT_URL = "{% url 'posts_attachment_delete' post.id %}";
    </script>

    <script type="text/javascript">
        let INITIAL = [
            {% for image in post.images %}
                '{{ image.original_filename }}',
            {% endfor %}

        ];

        let getUsedImages = function (currentText) {
            const matchedImagesGroups = currentText.match(/!\[(.*?)\]\(.+?\)/gm);
            if (matchedImagesGroups === null) {
                return [];
            }
            return matchedImagesGroups.map(function (currentValue, index, array) {
                // TODO: improve lazy matching group to catch first ( from $
                let img = currentValue.match(/\]\((.+?)\)$/)[0].slice(2, -1);

                // if its a video with preview
                if (img.indexOf(' ') > -1) {
                    let chunks = img.split(' ');
                    if (chunks[0].indexOf('youtube.com') > -1) return chunks[1];
                    if (chunks[0].indexOf('vimeo.com') > -1) return chunks[1]
                }

                // if its a gallery
                if (img.indexOf(',') > -1) return img.split(',');

                return img
            })
        };


        let countStats = function () {
            let currentText = $('#id_xmd').val()
            let usedImages = getUsedImages(currentText)

            let missingImages = [...new Set(usedImages.filter(x => !INITIAL.includes(x)))]
            let extraImages = [...new Set(INITIAL.filter(x => !usedImages.includes(x)))]

            return [missingImages, extraImages]
        }

        let updateStats = function () {
            let [missing, extra] = countStats()
            let missingClass = '',
                missingText = '',
                extraClass = '',
                extraText = '';


            if (missing.length > 0) {
                missingText = 'Не хватает картинок: ' + missing.join(', ');
                missingClass = 'active'
            } else {
                missingText = 'Все картинки приложены'
            }
            $('#images_status #missing').text(missingText).attr('class', missingClass)


            if (extra.length > 0) {
                extraText = 'Лишние картинки: ' + extra.join(', ');
                extraClass = 'active'
            } else {
                extraText = 'Лишних картинок нет'
            }
            $('#images_status #extra').text(extraText).attr('class', extraClass)
        };

        $(document).ready(function () {
            {% if request.user.user.preferences.magplan__xmd_editor_type == 'markdown' %}
                const simpleMDE = new SimpleMDE({
                    element: $("#id_xmd")[0],
                    spellChecker: false,
                    forceSync: true
                });
            {% endif %}

            updateStats();
            $("#id_xmd").on('change keyup paste', function () {
                updateStats()
            });
        })
    </script>
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
{% endblock %}