src/magplan/urls.py
# from django.conf.urls import url
from django.urls import path

from magplan.views import (
    api,
    articles,
    authors,
    ideas,
    index,
    issues,
    posts,
    preferences,
    sections,
    stages,
)

urlpatterns = [
    path("sections/", sections.index, name="sections_index"),
    path("stages/", stages.index, name="stages_index"),
    path(
        "ideas/<int:idea_id>/comments/", ideas.comments, name="ideas_comments"
    ),
    path("ideas/<int:idea_id>/approve/", ideas.approve, name="ideas_approve"),
    path("ideas/<int:idea_id>/vote/", ideas.vote, name="ideas_vote"),
    path("ideas/<int:idea_id>/", ideas.show, name="ideas_show"),
    path("ideas/", ideas.index, name="ideas_index"),
    path("articles/search", articles.search, name="articles_search"),
    path("articles/default", articles.default, name="articles_default"),
    path("articles/archived", articles.archived, name="articles_archived"),
    path("articles/advert", articles.advert, name="articles_advert"),
    path(
        "articles/whitelisted",
        articles.whitelisted,
        name="articles_whitelisted",
    ),
    path("articles/", articles.index, name="articles_index"),
    path("issues/<int:issue_id>/", issues.show, name="issues_show"),
    path("issues/new/", issues.create, name="issues_create"),
    path("issues/", issues.index, name="issues_index"),
    path(
        "posts/<int:post_id>/attachments/delete/",
        posts.attachment_delete,
        name="posts_attachment_delete",
    ),
    path(
        "posts/<int:post_id>/comments/", posts.comments, name="posts_comments"
    ),
    path(
        "posts/<int:post_id>/set_stage/",
        posts.set_stage,
        name="posts_set_stage",
    ),
    path("posts/<int:post_id>/edit/", posts.edit, name="posts_edit"),
    path(
        "posts/<int:post_id>/edit_meta/",
        posts.edit_meta,
        name="posts_edit_meta",
    ),
    path(
        "posts/<int:post_id>/download/",
        posts.download_content,
        name="posts_download_content",
    ),
    path(
        "posts/<int:post_id>/send_to_wp/",
        posts.send_to_wp,
        name="posts_send_to_wp",
    ),
    path("posts/<int:post_id>/", posts.show, name="posts_show"),
    path("posts", posts.create, name="posts_create"),
    path("api/issues/search/", api.issues_search, name="api_issues_search"),
    path("api/users/search/", api.authors_search, name="api_authors_search"),
    path("authors/new/", authors.new, name="authors_new"),
    path("authors/<int:user_id>/edit/", authors.edit, name="authors_edit"),
    path("authors/<int:user_id>/", authors.show, name="authors_show"),
    path("authors/", authors.index, name="authors_index"),
    path("settings/", preferences.index, name="preferences_index"),
    path("", index.index, name="index_index"),
]

src/magplan/models/idea.py
import os
import typing as tp

import html2text
from django.contrib.contenttypes.fields import GenericRelation
from django.core.mail import EmailMultiAlternatives
from django.db import models
from django.template.loader import render_to_string

from magplan.conf import settings as config
from magplan.models.abs import AbstractSiteModel, AbstractBase
from magplan.models.user import User
from magplan.xmd import render_md


NEW_IDEA_NOTIFICATION_PREFERENCE_NAME = "magplan__new_idea_notification"

class Idea(AbstractSiteModel, AbstractBase):
    AUTHOR_TYPE_NO = "NO"
    AUTHOR_TYPE_NEW = "NW"
    AUTHOR_TYPE_EXISTING = "EX"
    AUTHOR_TYPE_CHOICES = [
        (AUTHOR_TYPE_NO, "Нет автора"),
        (AUTHOR_TYPE_NEW, "Новый автор"),
        (AUTHOR_TYPE_EXISTING, "Существующий автор(ы)"),
    ]
    title = models.CharField(
        null=False, blank=False, max_length=255, verbose_name="Заголовок"
    )
    description = models.TextField(verbose_name="Описание")
    approved = models.BooleanField(null=True)
    editor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="editor"
    )
    post = models.OneToOneField(
        "Post", on_delete=models.SET_NULL, null=True, blank=True
    )
    comments = GenericRelation("Comment")
    author_type = models.CharField(
        max_length=2,
        choices=AUTHOR_TYPE_CHOICES,
        default=AUTHOR_TYPE_NO,
        verbose_name="Автор",
    )
    authors_new = models.CharField(
        max_length=255, null=True, blank=True, verbose_name="Новые автор"
    )
    authors = models.ManyToManyField(
        User, verbose_name="Авторы", related_name="authors", blank=True
    )

    def voted(self, user):
        vote = next((v for v in self.votes.all() if v.user_id == user.id), None)

        if vote:
            return True
        return False

    def _send_vote_notification(self, recipient: User) -> None:
        subject = f"Новая идея «{self.title}». Голосуйте!"

        context = {"idea": self, "APP_URL": os.environ.get("APP_URL")}
        message_html_content: str = render_to_string(
            "email/new_idea.html", context
        )
        message_text_content: str = html2text.html2text(message_html_content)

        msg = EmailMultiAlternatives(
            subject,
            message_text_content,
            config.PLAN_EMAIL_FROM,
            [recipient.email],
        )
        msg.attach_alternative(message_html_content, "text/html")
        msg.send()

    def send_vote_notifications(self) -> None:
        active_users: tp.List[User] = User.objects.filter(
            is_active=True
        ).exclude(id=self.editor_id)
        recipients: tp.List[User] = [
            user
            for user in active_users
            if user.preferences[NEW_IDEA_NOTIFICATION_PREFERENCE_NAME]
        ]

        for recipient in recipients:
            self._send_vote_notification(recipient)

    def __str__(self):
        return self.title

    class Meta:
        permissions = (
            ("edit_extended_idea_attrs", "Edit extended Idea attributes"),
            ("recieve_idea_email_updates", "Recieve email updates for Idea"),
        )

    @property
    def comments_(self):
        return self.comments.order_by("created_at").all

    @property
    def score(self):
        MAX_SCORE = 100

        all_scores = sum([v.score for v in self.votes.all()])
        max_scores = len(self.votes.all()) * MAX_SCORE

        return round(all_scores / max_scores * 100)

    @property
    def description_html(self):
        return render_md(self.description)


NEW_IDEA_NOTIFICATION_PREFERENCE_NAME = "magplan__new_idea_notification"

src/magplan/models/post.py
import datetime
import enum
import hashlib
import logging
import mimetypes
import os
import typing as tp
import urllib
from typing import List

import django
import requests
from botocore.exceptions import ClientError
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models import JSONField
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone

from magplan.conf import settings as config
from magplan.conf.settings import S3_STATIC_BASE_PATH
from magplan.integrations.images import S3Client
from magplan.integrations.posts import replace_images_paths, update_ext_db_xmd
from magplan.models import User
from magplan.models.abs import AbstractSiteModel, AbstractBase
from magplan.models.issue import Issue
from magplan.models.section import Section
from magplan.models.stage import Stage
from magplan.models.user import User
from magplan.xmd import render_md
from magplan.xmd.mappers import s3_public_mapper as s3_image_mapper, plan_internal_mapper as plan_image_mapper

WP_DATE_FORMAT_STRING = "%Y-%m-%d %H:%M:%S"
logger = logging.getLogger()


class Post(AbstractSiteModel, AbstractBase):
    # Used for external parser configuration
    PAYWALL_NOTICE_HEAD = '<div class="paywall-notice">'
    PAYWALL_NOTICE_BODY = "Продолжение статьи доступно только продписчикам"
    PAYWALL_NOTICE_TAIL = "</div>"
    PAYWALL_NOTICE_RENDERED = "{}{}{}".format(
        PAYWALL_NOTICE_HEAD, PAYWALL_NOTICE_BODY, PAYWALL_NOTICE_TAIL
    )

    @property
    def full_title(self) -> str:
        if self.kicker is None:
            return self.title

        separator = " " if self.kicker.endswith(("!", ":", "?")) else ". "
        return f"{self.kicker}{separator}{self.title}"

    def __str__(self) -> str:
        return self.full_title

    POST_FORMAT_DEFAULT = 0
    POST_FORMAT_FEATURED = 1
    POST_FORMAT_CHOICES = (
        (POST_FORMAT_DEFAULT, "Default"),
        (POST_FORMAT_FEATURED, "Featured"),
    )

    format = models.SmallIntegerField(
        choices=POST_FORMAT_CHOICES, default=POST_FORMAT_DEFAULT
    )

    POST_FEATURES_DEFAULT = 0
    POST_FEATURES_ARCHIVE = 1
    POST_FEATURES_ADVERT = 2
    POST_FEATURES_TRANSLATED = 2
    POST_FEATURES_CHOICES = (
        (POST_FEATURES_DEFAULT, "Default"),
        (POST_FEATURES_ARCHIVE, "Archive"),
        (POST_FEATURES_ADVERT, "Advert"),
        (POST_FEATURES_TRANSLATED, "Translated"),
    )
    features = models.SmallIntegerField(
        choices=POST_FEATURES_CHOICES, default=POST_FEATURES_DEFAULT
    )

    finished_at = models.DateTimeField(
        null=False,
        blank=False,
        default=django.utils.timezone.now,
        verbose_name="Дедлайн",
    )
    published_at = models.DateTimeField(
        null=True, blank=True, verbose_name="Дата публикации"
    )
    kicker = models.CharField(null=True, blank=True, max_length=255)
    slug = models.SlugField(
        null=True, blank=True, max_length=255, verbose_name="Слаг для URL"
    )
    title = models.CharField(
        null=True, blank=True, max_length=255, verbose_name="Заголовок статьи"
    )
    description = models.TextField(
        null=False, blank=True, verbose_name="Описание статьи"
    )
    views = models.IntegerField(default=0)
    is_paywalled = models.BooleanField(default=False)
    xmd = models.TextField(null=True)
    html = models.TextField(null=True)

    editor = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name="edited",
        verbose_name="Редактор",
    )
    authors = models.ManyToManyField(User, verbose_name="Авторы")
    stage = models.ForeignKey(
        Stage, on_delete=models.CASCADE, verbose_name="Этап"
    )
    issues = models.ManyToManyField(
        Issue, related_name="posts", verbose_name="Выпуски"
    )
    section = models.ForeignKey(
        Section,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        verbose_name="Раздел",
    )
    last_updater = models.ForeignKey(
        User,
        related_name="posts_updated",
        verbose_name="Кто последний обновлял",
        null=True,
        on_delete=models.SET_NULL,
    )

    meta = JSONField(default=dict)

    comments = GenericRelation("Comment")
    is_locked = models.BooleanField(default=False)
    css = models.TextField(
        null=True,
        blank=True,
        verbose_name="CSS-стили для статьи",
        help_text=("CSS, который будет применяться к превью статьи"),
    )

    def imprint_updater(self, user: User) -> None:
        """Update updated_at timestamp and set provided user as last_updater.

        `created_at` may be overwritten further on DB-hook level.
        .save() method should be explicitly called.
        """
        self.last_updater = user
        self.updated_at = datetime.datetime.now()

    @property
    def images(self):
        return list(
            filter(
                lambda a: a.type == Attachment.TYPE_IMAGE,
                self.attachment_set.all(),
            )
        )

    @property
    def pdfs(self):
        return list(
            filter(
                lambda a: a.type == Attachment.TYPE_PDF,
                self.attachment_set.all(),
            )
        )

    @property
    def files(self):
        return list(
            filter(
                lambda a: a.type == Attachment.TYPE_FILE,
                self.attachment_set.all(),
            )
        )

    @property
    def featured_image(self) -> tp.Optional["Attachment"]:
        return self.attachment_set.filter(
            type=Attachment.TYPE_FEATURED_IMAGE
        ).first()

    @property
    def assignee(self):
        if self.stage and self.stage.assignee:
            return self.stage.assignee
        elif self.editor:
            return self.editor
        else:
            return None

    @property
    def prev_stage_assignee(self):
        if self.stage.prev_stage and self.stage.prev_stage.assignee:
            return self.stage.prev_stage.assignee
        else:
            return self.editor

    @property
    def next_stage_assignee(self):
        if self.stage.next_stage and self.stage.next_stage.assignee:
            return self.stage.next_stage.assignee
        else:
            return self.editor

    @property
    def comments_(self):
        return self.comments.order_by("created_at").all

    @property
    def has_text(self):
        return self.xmd is not None and self.xmd != ""

    @property
    def is_default(self):
        return self.features == self.POST_FEATURES_DEFAULT

    @property
    def is_archive(self):
        return self.features == self.POST_FEATURES_ARCHIVE

    @property
    def is_advert(self):
        return self.features == self.POST_FEATURES_ADVERT

    @property
    def is_regular(self):
        return self.section.is_whitelisted == True

    @property
    def is_translated(self):
        return self.features == self.POST_FEATURES_TRANSLATED

    class Meta:
        permissions = (
            ("recieve_post_email_updates", "Recieve email updates for Post"),
            ("edit_extended_post_attrs", "Edit extended Post attributes"),
            # Direct article creation
            ("create_generic_post", "Create generic post"),
            ("create_archive_post", "Create archive post"),
            ("create_advert_post", "Create advert post"),
            ("create_regular_post", "Create regular post"),
            ("create_translated_post", "Create translated post"),
        )

    @property
    def is_overdue(self):
        if self.stage.slug in ("vault", "published"):
            return False
        return timezone.now() > self.finished_at

    @property
    def description_html(self):
        return render_md(self.description, render_lead=False)

    @property
    def wp_id(self):
        return self.meta.get("wpid")

    @property
    def lead(self) -> str:
        if not self.xmd:
            return ""

        paragraphs: List[str] = self.xmd.split("\n")
        for paragraph in paragraphs:
            cleaned_paragraph = paragraph.strip()
            if not cleaned_paragraph:
                continue

            if cleaned_paragraph.startswith("$"):
                cleaned_paragraph = cleaned_paragraph[1:]

            cleaned_paragraph = cleaned_paragraph.strip()
            return cleaned_paragraph

        return ""

    def build_xmd_blob(self, prepared_xmd: str) -> str:
        """Attaches CSS to XMD for remote CMS

        >>> self.css ='foo'
        'foo'

        >>> xmd = 'bar'
        'bar'

        >>> self.build_xmd_blob(self.xmd)
        %style type=text/css
        foo
        %style
        bar
        """
        OPENING_STYLE_TAG = "%style type=text/css"
        CLOSING_STYLE_TAG = "%style"

        if not prepared_xmd:
            return prepared_xmd

        if not self.css:
            return prepared_xmd

        return "{}\n{}\n{}\n{}".format(
            OPENING_STYLE_TAG, self.css, CLOSING_STYLE_TAG, prepared_xmd
        )

    def upload(self):
        """Uploads post, metadata and attachments to remote CMS

        * self images uploaded to S3.
        * self content uploaded to WP with uploaded S3 images urls

        This method is long-running, can cause time-outs
        and should be run ONLY in async tasks.
        """
        logger.debug("Staring Post.upload")
        if not self.wp_id:
            logger.warning("No wp_id, exiting")
            return

        for image in self.images:
            image.upload_to_storage()
        logger.debug("Uploaded images")

        # Upload to external DB
        prepared_xmd = replace_images_paths(
            xmd=self.xmd,
            attachments=self.images,
            mapper=s3_image_mapper,
        )
        logger.debug("Replaced images paths")

        upload_kwargs: tp.Dict[str, str] = {
            "xmd": prepared_xmd,
            "title": str(self),

src/magplan/models/vote.py
from django.db import models

from magplan.models.abs import AbstractBase
from magplan.models.idea import Idea
from magplan.models.user import User


class Vote(AbstractBase):
    SCORE_0 = 0
    SCORE_25 = 25
    SCORE_50 = 50
    SCORE_75 = 75
    SCORE_100 = 100
    SCORE_CHOICES = (
        (SCORE_0, "Против таких статей в «Хакере»"),
        (SCORE_25, "Не верю, что выйдет хорошо"),
        (SCORE_50, "Тема нормальная, но не для меня"),
        (SCORE_75, "Почитал бы, встретив в журнале"),
        (SCORE_100, "Ради таких статей мог бы подписаться"),
    )
    score = models.SmallIntegerField(choices=SCORE_CHOICES, default=SCORE_50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    idea = models.ForeignKey(
        Idea, on_delete=models.CASCADE, related_name="votes"
    )

    @property
    def score_humanized(self):
        return self.__class__.SCORE_CHOICES

src/magplan/templates/magplan/ideas/_approve_ideas.html
<h4>Аппрув идеи</h4>
<form action="{% url 'ideas_approve' idea.id %}"
      method="POST"
      accept-charset="utf-8">
    <div class="row">
        {% csrf_token %}
        <div class="col-6">
            <select name="approve" class="form-control">
                <option value="1">Принять идею</option>
                <option value="0">Отклонить идею</option>
            </select>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-success btn-block">Изменить</button>
        </div>

    </div>
</form>

src/magplan/templates/magplan/ideas/_authors_list.html
{# HACK: access enum values in templates #}
{% if idea.author_type == AUTHOR_TYPE_CHOICES.1.0 %} {# AUTHOR_TYPE_NEW #}
    <strong>Напишут новые авторы:</strong> {{ idea.authors_new }}
{% elif idea.author_type == AUTHOR_TYPE_CHOICES.2.0 %} {# AUTHOR_TYPE_EXISTING #}
    <strong>Напишут наши авторы:</strong>
    {% for author in idea.authors.all %}
        {% if perms.magplan.manage_authors %}
            <a href="{% url 'authors_show' author.id %}">{{ author }}</a>{% if forloop.last is False %},
        {% else %}.{% endif %}
        {% else %}
            {{ author }}{% if forloop.last is False %}, {% else %}.{% endif %}
        {% endif %}
    {% endfor %}
{% else %}
    Авторов для этой идеи пока нет.
{% endif %}

src/magplan/templates/magplan/ideas/_form_base.html
{% load widget_tweaks %}

<div class="row">
    <div class="col-12">
        <div class="form-group">
            {{ form.title.label }}
            {% if form.title.errors %}
                <ul class="errors">
                    {% for error in form.title.errors %}
                        <li>{{ error }}</li>{% endfor %}
                </ul>
            {% endif %}
            {{ form.title }}
        </div>
    </div>
</div>


<div class="row">
    <div class="col-12">
        <div class="form-group">
            {{ form.description.label }}
            {% if form.description.errors %}
                <ul class="errors">
                    {% for error in form.description.errors %}
                        <li>{{ error }}</li>{% endfor %}
                </ul>
            {% endif %}
            {{ form.description }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <div class="form-group">
            {{ form.author_type.label }}
            {% if form.author_type.errors %}
                <ul class="errors"> {% for error in form.author_type.errors %}
                    <li>{{ error }}</li> {% endfor %}
                </ul>
            {% endif %}
            {{ form.author_type }}
        </div>
    </div>
    <div class="col-6">
        <!--new authors-->
        <div id="authors_new" class="form-group" style="display: none;">
            <span class="label-hidable">{{ form.authors_new.label }}</span>
            {% if form.description.errors %}
                <ul class="errors">
                    {% for error in form.authors_new.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {{ form.authors_new }}
        </div>

        <!--existing authors-->
        <div id="authors" class="form-group" style="display: none;">
            <span class="label-hidable">{{ form.authors.label }}</span>
            {% if form.authors.errors %}
                <ul class="errors">
                    {% for error in form.authors.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% render_field form.authors data-url=api_authors_search_url %}
        </div>
    </div>
</div>

src/magplan/templates/magplan/ideas/_vote.html
{% load filters %}

<div class="row">
    <div class="col-12"><h4>Голосование за идею <span
            class="text-muted">(проголосовало {{ idea.votes.all|length }})</span>
    </h4></div>
</div>
<div class="row">
    {# if user already voted #}
    {% if idea|voted:request.user.user %}
        {% include 'magplan/ideas/_voting_results.html' %}
    {% else %}
        <div class="col-6">
            <strong>Выбери один из пунктов:</strong>
        </div>
        <div class="col-6">
            {% for i in 5|times %}
                <form method="POST" action="{% url 'ideas_vote' idea.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="score" value="{%  widthratio i 1 25 %}"/>
                    <input style="margin-bottom: 0.5rem;" type="submit" class="btn btn-block btn-{{ i|score_css_color_by_index }}"
                           value="{{ i|emoji_sign_by_index }} {{ i|humanize_score_index }}"/>
                </form>
            {% endfor %}
        </div>

    {% endif %}

</div>

src/magplan/templates/magplan/ideas/_voting_results.html
{% load filters %}

<div class="col-6">
    <strong>✅ Вы голосовали по этой идее.</strong>

    <hr>
    {% with current_score=idea.score %}
        <h4>Текущая оценка {{ current_score }}%</h4>


        <h6>Как принимаются решения</h6>
        <ul>
            <li><strong>75%–100%:</strong> идея принимается;</li>
            <li><strong>25%–74%:</strong> решает ответственный;</li>
            <li><strong>0%–24%:</strong> идея отклоняется.</li>
        </ul>
        <h6>
            Текущая рекомендация:
            {% if current_score < 25 %}
                отклонить статью.
            {% elif current_score > 24 and current_score < 75 %}
                решает ответственный.
            {% else %}
                принять статью.
            {% endif %}
        </h6>
    {% endwith %}

    {% if perms.magplan.edit_extended_idea_attrs %}
        {% include 'magplan/ideas/_approve_ideas.html' %}
    {% endif %}
</div>
<div class="col-6">
    <table class="table table-bordered">
        <thead>
        <th>Голосующий</th>
        <th>Мнение</th>
        </thead>
        <tbody>
        {% for vote in idea.votes.all %}
            <tr>
                <td>{{ vote.user }}</td>
                <td>{{ vote.score|humanize_score }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

src/magplan/templates/magplan/ideas/index.html
{% extends "layout_plan.html" %}
{% block title %}Идеи{% endblock %}
{% block styles %}
<style>
    /* Fix for select2 initial render in hidden mode */
    .select2.select2-container {
        width: 100% !important; }

    #authors_new.form-group>span.label-hidable,
    #authors.form-group>span.label-hidable {
        visibility: hidden;
    }
</style>
{% endblock %}
{% block content %}
<h1>Идеи</h1>
<div class="card border-success">

    <div class="card-header text-white bg-success">Предложить идею статьи</div>
    <div class="card-body">
        <form action="{% url 'ideas_index' %}" method="post" accept-charset="utf-8">
            {% csrf_token %}
            {% include 'magplan/ideas/_form_base.html' %}
            <button type="submit" class="btn btn-success float-right">На голосование!</button>
        </form>
    </div>
</div>
<br />
<br />

<h2>На голосовании и ожидании</h2>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link {% if filter_ == none %}active{% endif %}" href="{% url 'ideas_index' %}">Все</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if filter_ == 'voted' %}active{% endif %}" href="{% url 'ideas_index' %}?filter=voted">На
            голосовании</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if filter_ == 'self' %}active{% endif %}"
            href="{% url 'ideas_index' %}?filter=self">Свои</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if filter_ == 'approved' %}active{% endif %}"
            href="{% url 'ideas_index' %}?filter=approved">Принятые</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if filter_ == 'rejected' %}active{% endif %}"
            href="{% url 'ideas_index' %}?filter=rejected">Отклоненные</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if filter_ == 'no_author' %}active{% endif %}"
            href="{% url 'ideas_index' %}?filter=no_author">Нет автора</a>
    </li>
</ul>
<br />

<div class="table-responsive">
    <table class="table table-striped table-sm table-interactive">
        <thead>
            <th>Редактор</th>
            <th>Название</th>
            <th>Голосование</th>
        </thead>
        <tbody>

            {% for idea in ideas %}
            <tr class="">
                <td>{{ idea.editor }} </td>
                <td>
                    <a href="{% url 'ideas_show' idea.id %}">{{ idea.title }}</a>
                    <p>{{ idea.description|truncatechars:512 }}</p>
                <td>
                    {% if idea.approved is True %}
                    <span class="badge badge-success">Одобрено</span>
                    {% elif idea.approved is False %}
                    <span class="badge badge-danger">Отклонено</span>
                    {% else %}
                    Идет голосование. Проголосовали {{ idea.voted }}
                    {% endif %}

                    {% if idea.post %}
                    <br />
                    <br />
                    <a href="{% url 'posts_show' idea.post.id %}">Посмотреть
                        статью</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}
{% block scripts %}
<script type='text/javascript'>
    $('#id_author_type').change(function () {
        let $newContainer = $('#id_authors_new').parent()
        let $extContainer = $('#id_authors').parent()
        let newValue = $(this).val()

        $newContainer.hide()
        $extContainer.hide()

        if (newValue === 'NW') {
            $newContainer.show()
        } else if (newValue === 'EX') {
            $extContainer.show()
        }
    })
</script>
{% endblock %}

src/magplan/templates/magplan/ideas/show.html
{% extends "layout_plan.html" %}
{% block title %}Идея «{{ idea.title }}»{% endblock %}
{% load filters %}
{% block styles %}
{% endblock %}
{% block content %}
    <h2 id='title' class="text-muted">{{ idea.title }}</h2>
    <p>
        <strong>Предложил</strong> {{ idea.editor }}
    </p>
    <p>
        {% with idea=idea AUTHOR_TYPE_CHOICES=AUTHOR_TYPE_CHOICES %}
            {% include 'magplan/ideas/_authors_list.html' %}
        {% endwith %}
    </p>
    <div id="description">{{ idea.description_html|safe }}</div>

    {% if idea.approved is None %}
        {% include 'magplan/ideas/_vote.html' %}
    {% else %}
        <br>

        {% if idea.approved == True %}
            <h2 style="padding-bottom: 0.6rem;"><strong>По результатам голосования идея статьи одобрена! 👍 😊 🚀</strong></h2>
            <div class="row">
                {% include 'magplan/ideas/_voting_results.html' %}
            </div>
            <br>
            <div class="card border-success">
                {% if idea.post %}
                    <div class="card-header text-white bg-primary">Есть статья!</div>
                    <div class="card-body"> К этой идее создана статья:
                        <a class="btn btn-secondary btn-sm" href="{% url 'posts_show' idea.post.id %}">посмотреть</a>
                    </div>
                {% else %}
                    <div class="card-header text-white bg-success">Сделать из идеи статью</div>
                    <div class="card-body text-success">
                        <form action="{% url 'posts_create' %}" method="POST" accept-charset="utf-8">
                            {% csrf_token %}
                            {% include 'magplan/posts/_form_base.html' %}
                            <input type="hidden" name="idea_id" value="{{ idea.id }}"/>
                            <button type="submit" class="btn btn-success float-right">Создать статью из идеи!</button>
                        </form>
                    </div>
                {% endif %}


            </div>
        {% else %}
            <h2 style="padding-bottom: 0.6rem;">По результатам голосования идея статьи отклонена ❌ 😵 ⛈</h2>
            <p>Сделать из нее статью на данный момент нельзя.</p>
            <div class="row">
                {% include 'magplan/ideas/_voting_results.html' %}
            </div>
        {% endif %}
    {% endif %}
    <br/>

    {# Support for generic comments template #}
    {% with comments=idea.comments_ form=comment_form action_url=idea|url_for_idea_comments %}
        {% include 'magplan/partials/comments.html' %}
    {% endwith %}

{% endblock %}
{% block scripts %}
    <script type="text/javascript">
        $('.issues-suggestions .suggestion a').click(function (e) {
            e.preventDefault()
            let id = $(this).data('id')

            $('#id_issues').val(id).trigger('change');
        })
    </script>
{% endblock %}